use SKBUILD_BUILD_VERBOSE instead of SKBUILD_CMAKE_VERBOSE (#377)
Proposes switching from `SKBUILD_CMAKE_VERBOSE` to
`SKBUILD_BUILD_VERBOSE` in wheel-building scripts in
`rapids-build-utils`.

Setting `SKBUILD_CMAKE_VERBOSE` in the environment causes an unavoidable
build-time exception when using `scikit-build-core>=0.10.0` and setting
`minimum-version = "0.10.0"` in `scikit-build-core`.

```text
ERROR: Cannot set cmake.verbose if minimum-version is set to 0.10 or higher
```

([build
link](https://github.com/rapidsai/rmm/actions/runs/10274129734/job/28430178007?pr=1637#step:7:1878))

See
https://scikit-build-core.readthedocs.io/en/latest/configuration.html#verbosity

> Changed in version 0.10: cmake.verbose was renamed to build.verbose.

## Notes for Reviewers

For more context, see the conversation on that PR and
https://github.com/rapidsai/build-planning/issues/58.